name: Run Pytest 3.7

on:
  push:
    branches: 
      - master
    paths:
      - 'vectorai/**'
      - 'tests/**'
      - 'setup.py'
  pull_request:
    branches:
      - master
    paths:
      - 'vectorai/**'
      - 'tests/**'
      - 'setup.py'
      
jobs:
  run_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pytest 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .['all']
    - name: Run Pytest
      env:
        USERNAME: ${{ secrets.USERNAME }}
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        pip install pytest
        pip install tensorflow==2.2.0
        pip install transformers==3.0.2
        pytest --use_client
